# -*- coding: utf-8 -*-
"""호텔리뷰.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wR7ojfNA2nrvp71hY0_mu31sf4dJzQXm

##필요한 라이브러리 다운로드
"""

# 코랩을 시작할 때 아래코드를 한 번 돌려줍니다.
!pip install selenium
!apt-get update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

"""##해당 Agoda 웹은 동적으로 작동되므로 Selenium을 사용함"""

from selenium import webdriver
from selenium.webdriver.common.by import By # class 태그나, id태그의 속성값을 가져오려고 합니다.
import time
# colab에서 selenium을 돌리기 위한 옵션들
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome(options=chrome_options)
#아고다 이동
url = 'https://www.agoda.com/the-shilla-jeju/hotel/jeju-island-kr.html'
driver.get(url)

#호텔리뷰를 찾고 호텔리뷰 개수를 확인
pagination_links = driver.find_elements(By.CSS_SELECTOR, '.Review-paginator-number')


for link in pagination_links:
    # JavaScript를 사용하여 클릭
    driver.execute_script("arguments[0].click();", link)
       # 페이지 로딩을 위해 충분한 시간 대기
    time.sleep(2)
        # 이용후기 요소들 가져오기
    review_num = driver.find_element(By.CLASS_NAME, 'Review__SummaryContainer--left.Review__SummaryContainer__Text').text



review_num

time.sleep(2)
# 모든 이용후기를 담을 리스트
reviews_by_date = {}
reviews_by_date['review_content'] = []
reviews_by_date['reviewer_info_element'] = []
reviews_by_date['date_text'] = []

# 페이지 전환을 위한 링크 요소들 찾기
pagination_links = driver.find_elements(By.CSS_SELECTOR, '.Review-paginator-number')
# length = len(pagination_links)
link = pagination_links[0]
driver.execute_script("arguments[0].click();", link)

time.sleep(2)


"""##제주도 신라호텔 리뷰와 날짜를 딕셔너리 형태로 크롤링"""

    # 이용후기 요소들 가져오기
review_elements = driver.find_elements(By.CLASS_NAME, 'Review-comment')
    # 각 이용후기 요소에서 텍스트와 날짜 추출하여 딕셔너리에 추가
for review_element in review_elements:

    # 리뷰
    review_content = review_element.find_element(By.CLASS_NAME, 'Review-comment-body').text.strip()
    reviews_by_date['review_content'].append(review_content)
    
    
    # 리뷰어 정보 요소
    reviewer_info_element = review_element.find_element(By.CLASS_NAME, 'Review-comment-reviewer[data-info-type="stay-detail"]')
    # reviews_by_date['reviewer_info_element'].append(reviewer_info_element)
   

    # 리뷰 날짜 
    date_text = reviewer_info_element.find_element(By.TAG_NAME, 'span').text.strip()
    reviews_by_date['date_text'].append(date_text)

pagination_links = driver.find_elements(By.CSS_SELECTOR, '.Review-paginator-number')[1]
driver.execute_script("arguments[0].click();", pagination_links )


time.sleep(2)


    # 이용후기 요소들 가져오기
review_elements = driver.find_elements(By.CLASS_NAME, 'Review-comment')
    # 각 이용후기 요소에서 텍스트와 날짜 추출하여 딕셔너리에 추가
for review_element in review_elements:
    
    # 리뷰
    review_content = review_element.find_element(By.CLASS_NAME, 'Review-comment-body').text.strip()
    reviews_by_date['review_content'].append(review_content)
    
    
    # 리뷰어 정보 요소
    reviewer_info_element = review_element.find_element(By.CLASS_NAME, 'Review-comment-reviewer[data-info-type="stay-detail"]')
    # reviews_by_date['reviewer_info_element'].append(reviewer_info_element)
   

    # 리뷰 날짜 
    date_text = reviewer_info_element.find_element(By.TAG_NAME, 'span').text.strip()
    reviews_by_date['date_text'].append(date_text)

pagination_links = driver.find_elements(By.CSS_SELECTOR, '.Review-paginator-number')[2]
driver.execute_script("arguments[0].click();", pagination_links )

time.sleep(2)

for i in tqdm(range(page_count - 2)):

    time.sleep(1)
    review_elements = driver.find_elements(By.CLASS_NAME, 'Review-comment')
        # 각 이용후기 요소에서 텍스트와 날짜 추출하여 딕셔너리에 추가
    
    for review_element in review_elements:

        # 리뷰
        review_content = review_element.find_element(By.CLASS_NAME, 'Review-comment-body').text.strip()
        reviews_by_date['review_content'].append(review_content)
        
        
        # 리뷰어 정보 요소
        reviewer_info_element = review_element.find_element(By.CLASS_NAME, 'Review-comment-reviewer[data-info-type="stay-detail"]')
        # reviews_by_date['reviewer_info_element'].append(reviewer_info_element)
    

        # 리뷰 날짜 
        date_text = reviewer_info_element.find_element(By.TAG_NAME, 'span').text.strip()
        reviews_by_date['date_text'].append(date_text)


    pagination_links = driver.find_elements(By.CSS_SELECTOR, '.Review-paginator-number')[4]
    driver.execute_script("arguments[0].click();", pagination_links )


driver.quit()


reviews_by_date
